name: survey_project
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0
  bloc: ^9.0.0
  cached_network_image: ^3.4.1
  carousel_slider: ^5.1.1
  connectivity_plus: ^6.1.5
  crypto: ^3.0.6
  cupertino_icons: ^1.0.8
  device_info_plus: ^11.5.0
  dio: ^5.9.0
  draggable_widget: ^2.0.0
  double_back_to_close: ^2.0.0
  dropdown_button2: ^2.3.9
  encrypted_shared_preferences: 3.0.1
  equatable: any
  extended_masked_text: ^3.0.1
  face_camera: ^0.1.4
  file_picker: ^10.3.1
  firebase_core: ^3.15.2
  firebase_messaging: ^15.2.10
  flexible_animated_container: ^0.0.5
  flutter_ai_toolkit: ^0.9.2
  flutter_bloc: ^9.1.1
  flutter_cache_manager: ^3.4.1
  flutter_dotenv: ^5.2.1
  flutter_facebook_auth: ^7.1.2
  flutter_image_compress: ^2.4.0
  flutter_launcher_icons: ^0.14.4
  flutter_markdown_plus: ^1.0.3
  flutter_local_notifications: ^19.4.0
  flutter_overlay_window: any
  flutter_rating: ^2.0.2
  flutter_rating_stars: ^1.1.0
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  fluttertoast: ^8.2.12
  font_awesome_flutter: ^10.9.0
  gap: ^3.0.1
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  google_fonts: ^6.3.0
  google_maps_flutter: ^2.12.3
  google_nav_bar: ^5.0.7
  http_parser: ^4.1.2
  intl: ^0.20.2
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  local_auth: ^2.3.0
  lottie: ^3.3.1
  maps_launcher: ^3.0.0+1
  mime: ^2.0.0
  overlay_support: ^2.1.0
  path: any
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  pin_code_fields: ^8.0.1
  provider: ^6.1.5
  qr_flutter: ^4.1.0
  rxdart: ^0.28.0
  responsive_sizer: ^3.3.1
  responsive_framework: ^1.5.1
  shared_preferences: ^2.5.3
  timeago: ^3.7.1
  tuple: ^2.0.2
  url_launcher: ^6.3.2
  signature: ^6.3.0
  video_player: ^2.10.0
  video_thumbnail: ^0.5.6
  webview_flutter: ^4.13.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  flutter_lints: ^6.0.0
  isar_generator: ^3.1.0+1

dependency_overrides:
  camera: ^0.11.0+2
  capture_identity: ^1.0.1
  firebase_core_platform_interface: ^6.0.0
  intl: ^0.19.0  # Force compatibility between timeago and intl

flutter_icons:
  image_path_android: "assets/logo/app_logo.png"
  image_path_ios: "assets/logo/app_logo.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/logo/
    - assets/json/
    #    - assets/temporary/
    - .env


